### ISSUE TITLE
TypeError when importing the protocol definitions for generator, protobuf python

### ISSUE THREAD

**Issue by lorepieri8** [AnyLedger/anyledger-wallet#168]
**Describe the bug**
TypeError when importing the protocol definitions for generator, protobuf python

**To Reproduce**
x86 build, ninja

**Expected behavior**
ninja without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (docker)

**Additional context**
```
root@3e5b46fa1a8b:~/anyledger-wallet/build# cmake -GNinja ../
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3") 
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- x86 build!
-- Found GTest: /usr/local/lib/libgtest.a  
-- Found Threads: TRUE  
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
---------------
-- Configuring done
-- Generating done
-- Build files have been written to: /root/anyledger-wallet/build
root@3e5b46fa1a8b:~/anyledger-wallet/build# ninja
[3/63] Performing download step (git clone) for 'nanopb'
Cloning into 'nanopb'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[7/63] Performing configure step for 'nanopb'
-- The C compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/anyledger-wallet/build/nanopb/src/nanopb-build
[8/63] Performing build step for 'nanopb'
[1/5] Building C object CMakeFiles/protobuf-nanopb-static.dir/pb_common.c.o
[2/5] Generating nanopb_pb2.py
[3/5] Building C object CMakeFiles/protobuf-nanopb-static.dir/pb_encode.c.o
[4/5] Building C object CMakeFiles/protobuf-nanopb-static.dir/pb_decode.c.o
[5/5] Linking C static library libprotobuf-nanopb.a
[9/63] Performing install step for 'nanopb'
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /root/anyledger-wallet/build/install/./lib/python3.6/site-packages/nanopb/proto/nanopb_pb2.py
-- Installing: /root/anyledger-wallet/build/install/./lib/python3.6/site-packages/nanopb/nanopb_generator.py
-- Installing: /root/anyledger-wallet/build/install/./lib/python3.6/site-packages/nanopb/protoc-gen-nanopb
-- Installing: /root/anyledger-wallet/build/install/lib/libprotobuf-nanopb.a
-- Installing: /root/anyledger-wallet/build/install/lib/cmake/nanopb-targets.cmake
-- Installing: /root/anyledger-wallet/build/install/lib/cmake/nanopb-targets-noconfig.cmake
-- Installing: /root/anyledger-wallet/build/install/lib/cmake/nanopb-config.cmake
-- Installing: /root/anyledger-wallet/build/install/lib/cmake/nanopb-config-version.cmake
-- Installing: /root/anyledger-wallet/build/install/lib/cmake/FindNanopb.cmake
-- Installing: /root/anyledger-wallet/build/install/include/pb.h
-- Installing: /root/anyledger-wallet/build/install/include/pb_common.h
-- Installing: /root/anyledger-wallet/build/install/include/pb_encode.h
-- Installing: /root/anyledger-wallet/build/install/include/pb_decode.h
[19/63] Performing download step (git clone) for 'trezor-crypto-lib'
Cloning into 'trezor-crypto'...
Already on 'master'
Your branch is up to date with 'origin/master'.
Submodule 'tests/wycheproof' (https://github.com/google/wycheproof) registered for path 'tests/wycheproof'
Cloning into '/root/anyledger-wallet/build/thirdparty/trezor-crypto/tests/wycheproof'...
Submodule path 'tests/wycheproof': checked out '2904be69e9d666bf3064fdc15093747e695cfae6'
[26/63] Performing configure step for 'trezor-crypto-lib'
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/anyledger-wallet/build/trezor-crypto/src/trezor-crypto-lib-build
[27/63] Performing build step for 'trezor-crypto-lib'
[1/29] Building C object CMakeFiles/trezor-crypto.dir/base32.c.o
[2/29] Building C object CMakeFiles/trezor-crypto.dir/address.c.o
[3/29] Building C object CMakeFiles/trezor-crypto.dir/base58.c.o
[4/29] Building C object CMakeFiles/trezor-crypto.dir/bip32.c.o
[5/29] Building C object CMakeFiles/trezor-crypto.dir/blake256.c.o
[6/29] Building C object CMakeFiles/trezor-crypto.dir/bignum.c.o
[7/29] Building C object CMakeFiles/trezor-crypto.dir/bip39.c.o
[8/29] Building C object CMakeFiles/trezor-crypto.dir/cash_addr.c.o
[9/29] Building C object CMakeFiles/trezor-crypto.dir/blake2b.c.o
[10/29] Building C object CMakeFiles/trezor-crypto.dir/curves.c.o
[11/29] Building C object CMakeFiles/trezor-crypto.dir/blake2s.c.o
[12/29] Building C object CMakeFiles/trezor-crypto.dir/hasher.c.o
[13/29] Building C object CMakeFiles/trezor-crypto.dir/ecdsa.c.o
[14/29] Building C object CMakeFiles/trezor-crypto.dir/hmac.c.o
[15/29] Building C object CMakeFiles/trezor-crypto.dir/groestl.c.o
[16/29] Building C object CMakeFiles/trezor-crypto.dir/memzero.c.o
[17/29] Building C object CMakeFiles/trezor-crypto.dir/nem.c.o
[18/29] Building C object CMakeFiles/trezor-crypto.dir/rand.c.o
[19/29] Building C object CMakeFiles/trezor-crypto.dir/pbkdf2.c.o
[20/29] Building C object CMakeFiles/trezor-crypto.dir/nist256p1.c.o
[21/29] Building C object CMakeFiles/trezor-crypto.dir/rc4.c.o
[22/29] Building C object CMakeFiles/trezor-crypto.dir/rfc6979.c.o
[23/29] Building C object CMakeFiles/trezor-crypto.dir/ripemd160.c.o
[24/29] Building C object CMakeFiles/trezor-crypto.dir/script.c.o
[25/29] Building C object CMakeFiles/trezor-crypto.dir/secp256k1.c.o
[26/29] Building C object CMakeFiles/trezor-crypto.dir/segwit_addr.c.o
[27/29] Building C object CMakeFiles/trezor-crypto.dir/sha3.c.o
[28/29] Building C object CMakeFiles/trezor-crypto.dir/sha2.c.o
[29/29] Linking C static library libtrezor-crypto.a
[28/63] Performing install step for 'trezor-crypto-lib'
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /root/anyledger-wallet/build/install/lib/libtrezor-crypto.a
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/address.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/base32.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/base58.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/bignum.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/bip32.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/bip39.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/bip39_english.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/blake256.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/blake2_common.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/blake2b.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/blake2s.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/cash_addr.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/check_mem.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/curves.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ecdsa.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/groestl.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/groestl_internal.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/hasher.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/hmac.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/memzero.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/nem.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/nist256p1.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/options.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/pbkdf2.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/rand.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/rc4.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/rfc6979.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ripemd160.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/script.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/secp256k1.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/segwit_addr.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/sha2.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/sha3.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/chacha20poly1305.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/ecrypt-config.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/ecrypt-machine.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/ecrypt-portable.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/ecrypt-sync.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/ecrypt-types.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/poly1305-donna-32.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/poly1305-donna.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/chacha20poly1305/rfc7539.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/curve25519-donna-32bit.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/curve25519-donna-helpers.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/curve25519-donna-scalarmult-base.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-donna-32bit-tables.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-donna-basepoint-table.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-donna-impl-base.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-donna-portable.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-donna.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-hash-custom-keccak.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-hash-custom-sha3.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-hash-custom.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-keccak.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519-sha3.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/ed25519.h
-- Installing: /root/anyledger-wallet/build/install/include/trezor-crypto/ed25519-donna/modm-donna-32bit.h
[40/63] Compiling /root/anyledger-wallet/sawtooth/protos/transaction.proto protobuf
FAILED: sawtooth/transaction.pb.c 
cd /root/anyledger-wallet && protoc --plugin=/root/anyledger-wallet/build/thirdparty/nanopb/generator/protoc-gen-nanopb -I/root/anyledger-wallet/sawtooth/protos --nanopb_out=/root/anyledger-wallet/build/sawtooth /root/anyledger-wallet/sawtooth/protos/transaction.proto

         ****************************************************************************
         *** Got TypeError when importing the protocol definitions for generator. ***
         *** This usually means that the protoc in your path doesn't match the    ***
         *** Python protobuf library version.                                     ***
         ***                                                                      ***
         *** Please check the output of the following commands:                   ***
         *** which protoc                                                         ***
         *** protoc --version                                                     ***
         *** python -c 'import google.protobuf; print(google.protobuf.__file__)'  ***
         *** If you are not able to find the python protobuf version using the    ***
         *** above command, use this command.                                     ***
         *** pip freeze | grep -i protobuf                                        ***
         ****************************************************************************
    
Traceback (most recent call last):
  File "/root/anyledger-wallet/build/thirdparty/nanopb/generator/nanopb_generator.py", line 39, in <module>
    import proto.nanopb_pb2 as nanopb_pb2
  File "/root/anyledger-wallet/build/thirdparty/nanopb/generator/proto/nanopb_pb2.py", line 26, in <module>
    dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
[42/63] Building CXX object examples/tests/src/CMakeFiles/test_tx.dir/test_tx.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by lorepieri8** [comment]
Switching to the right protobuf version fix the issue:
https://github.com/tensorflow/models/issues/3995#issuecomment-387984935
